ClothesStore/ClothesStore/apps/Products/urls.py
from django.urls import path, include
from . import views

app_name = 'Products'
urlpatterns = [
    path('', views.index, name='index'),
    path('women/', views.women_view, name='women'),
    path('kids/', views.kids_view, name='kids'),
    path('<int:product_id>/',views.detail, name="detail"),
    path('<int:product_id>/leave_comment', views.leave_comment, name="leave_comment"),
    path('search/<int:product_id>/', views.search, name='search'),
    path('add_to_cart/', views.add_to_cart_view, name='add_to_cart'),
    path('remove_from_cart/', views.remove_from_cart_view, name='remove_from_cart'),
    # path('change_item_qty/', change_item_qty, name='change_item_qty'),
    path('cart/', views.cart_view,name='cart'),
]

ClothesStore/ClothesStore/apps/Users/urls.py
from django.urls import path
from . import views

app_name= 'Users'
urlpatterns = [
               path('signIn', views.LoginFormView.as_view(), name= 'signIn'),
               # path('register', views.registerView.as_view(), name="register"),
               path("user/", views.profile, name="profile"),
               path("logout", views.LogoutView.as_view(), name="logout"),
    # path('signIn', views.signIn, name='signIn'),
                path('register', views.register, name="register"),
    # path('register', views.RegisterFormView.as_view(), name='register')
]

ClothesStore/ClothesStore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls),
    path('', include('Products.urls')),
    path('user/', include('Users.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

ClothesStore/ClothesStore/apps/Products/models.py
from django.db import models
from django.utils import timezone
import datetime
from django.forms import ModelForm
from django.conf import settings
################
from django.db.models.signals import pre_save
from django.utils.text import slugify
from django.core.validators import MaxValueValidator, MinValueValidator
from django.conf import settings


class Category(models.Model):
    name = models.CharField(max_length=40)
    slug = models.SlugField(max_length=40)
    is_active= models.BooleanField(default=True)
    def __str__(self):
        return self.name

def pre_save_category_slug(sender, instance, *args, **kwargs):
	if not instance.slug:
		slug = slugify(instance.name)

		instance.slug = slug

pre_save.connect(pre_save_category_slug,sender=Category)

class Subcategories(models.Model):
    subcategories_name=models.CharField(max_length=40)
    is_active= models.BooleanField(default=True)
    def __str__(self):
        return self.subcategories_name

class Brand(models.Model):
    brand_name=models.CharField(max_length=20)
    is_active= models.BooleanField(default=True)
    def __str__(self):
        return self.brand_name

class ProductManager(models.Manager):
	"""docstring for ProductManager"""
	def all(self, *args, **kwargs):
		return super(ProductManager, self).get_queryset().filter(available=True)

class Product(models.Model):
    category = models.ForeignKey(Category, on_delete = models.CASCADE)
    subcategories_name = models.ForeignKey(Subcategories, on_delete=models.CASCADE)
    brand = models.ForeignKey(Brand, on_delete = models.CASCADE)
    product_name=models.CharField( max_length=50,blank=True, default=None, null=True)
    product_description = models.TextField(blank=True, default=None, null=True)
    product_price=models.FloatField(blank=True, default=None, null=True)
    discount = models.IntegerField(default=0)
    male="Man"
    female="Woman"
    kids="Kid"
    gender_product=(
                   (male,"Man"),
                   (female,"Women"),
                   (kids, "Kid")
    )
    product_num_size = models.IntegerField(blank=True, default=None, null=True, validators=[MaxValueValidator(45), MinValueValidator(12)])
    product_gender = models.CharField(max_length=5, choices=gender_product, default=male)
    eXtraSmall='XS'
    small="S"
    medium='M'
    large='L'
    eXtraLarge='XL'
    eXtra_eXtraLarge='XXL'
    size_choice=(
                 (eXtraSmall,"XS"),
                 (small, "S"),
                 (medium, "M"),
                 (large, "L"),
                 (eXtraLarge, "XL"),
                 (eXtra_eXtraLarge, "XXL")
    )
    product_size=models.CharField(max_length=3,choices=size_choice,default=small, blank=True, null=True)
    product_quantity=models.PositiveIntegerField()
    available = models.BooleanField(default=True, verbose_name="Доступен")
    # objects = ProductManager()
    # product_pub_date = models.DateTimeField( default = timezone.now, editable = False)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    update = models.DateTimeField(auto_now_add=False, auto_now=True)
    def __str__(self):
        return (self.product_name +" " + str(self.product_price)+' Tg')

class Like(models.Model):
    product=models.ForeignKey(Product, on_delete=models.CASCADE)
    author=models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    heart_click= models.IntegerField(default=0)

class ProductImage(models.Model):
    product=models.ForeignKey(Product, blank=True, null=True, default=None, on_delete=models.CASCADE)
    product_image = models.ImageField(upload_to="products/", blank = True)
    is_main = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    update = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return '%s' % self.id


# class Shoe(models.Model):
#     shoe_name=models.CharField('Name of Shoe', max_length=50)
#     shoe_price=models.FloatField('Price of Shoe, Tg')
#     shoe_image = models.ImageField(upload_to="images/", blank = True)
#     male="Man"
#     female="Woman"
#     kids="Kid"
#     gender_product=(
#                    (male,"Man"),
#                    (female,"Women"),
#                    (kids, "Kid")
#     )
#     shoe_gender = models.CharField('Gender', max_length=5, choices=gender_product, default=male)
#     shoe_size=models.CharField('Size',max_length=2,validators=[MaxValueValidator(45), MinValueValidator(12)])
#     shoe_quantity=models.PositiveIntegerField("Quantity of products")
#     shoe_pub_date = models.DateTimeField("product Date and Time" , default = timezone.now, editable = False)
#     def __str__(self):
#         return (self.shoe_name +" " + str(self.shoe_price)+'Tg')

class Comment(models.Model):
    comment_text = models.TextField("Comment text")
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    # shoe = models.ForeignKey(Shoe, on_delete=models.CASCADE)
    author_name = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    comment_pub_date = models.DateTimeField("Coment Date and Time" , default = timezone.now, editable = False)
    def __str__(self):
        return self.comment_text


class CartItem(models.Model):
    product=models.ForeignKey(Product, on_delete=models.CASCADE)
    qty=models.PositiveIntegerField(default=1)
    item_total=models.DecimalField(max_digits=9, decimal_places=2, default=0.00)

    def __str__(self):
        return "Cart item for product{0}".format(self.products.title)

class Cart(models.Model):

	items = models.ManyToManyField(CartItem, blank=True)
	cart_total = models.DecimalField(max_digits=9,decimal_places=2,default=0.00)



	def __str__(self):
		return str(self.id)

	def get_absolute_url(self):
		return reverse('product_details', kwargs={'product_slug': self.slug})


	def add_to_cart(self,product_slug):
		cart = self
		product = Product.objects.get(slug=product_slug)
		new_item, _ =CartItem.objects.get_or_create(product=product,item_total=product.price)
		# cart = Cart.objects.first()

		if new_item  in cart.items.all():

			return HttpResponseRedirect('Этот товап имеется')


		if new_item not in cart.items.all():
			cart.items.add(new_item)
			cart.save()
			return HttpResponseRedirect('/cart/')

	def remove_from_cart(self,product_slug):
		cart = self
		product = Product.objects.get(slug=product_slug)

		for cart_item in cart.items.all():
			if cart_item.product == product:
				cart.items.remove(cart_item)
				cart.save()
				return HttpResponseRedirect('/cart/')

		# cart = Cart.objects.first()

ClothesStore/ClothesStore/apps/Users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class SimpleUser(AbstractUser):
    user_name= models.CharField("Name", max_length=20,null=True, blank=True)
    user_surname = models.CharField("Surname", max_length=20,null=True, blank=True)
    user_email = models.EmailField('Email')
    user_phone_num = models.CharField('Country of User', max_length = 48, blank = True, null=True, default=None)
    user_avatar=models.ImageField(upload_to='users/', null=True, blank=True)
    user_birthdate=models.DateField(null=True, blank=True)

    def __str__(self):
        return (self.username)



class CreditCard(models.Model):
    user = models.ForeignKey(SimpleUser, on_delete=models.CASCADE)
    card_name=models.CharField("Card Name", max_length=15)
    card_number= models.IntegerField("Card number")
    # card_date=models.DateField("VALID THRU", widget=models.dat
    card_AS=models.IntegerField("Authorization Signature")

ClothesStore/ClothesStore/apps/Orders/forms.py
from django import forms
from .models import Order


class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['customer', 'status' , 'total_price']

ClothesStore/ClothesStore/apps/Products/forms.py
# from django import forms
# from .models import Comment
#
# class CommentForm(forms.Form):
#     author_name = models.CharField(label ='Name of Author', max_length = 50)
#     comment_text = models.TextField("Comment text", max_length = 200)
#
#     def save(self):
#         new_comment = Comment.objects.create(
#             author_name= self.cleaned_data['author_name'],
#             comment_text = self.cleaned_data['comment_text']
#         )
#         return new_comment

ClothesStore/ClothesStore/apps/Orders/views.py
from django.shortcuts import render
from .models import *
from Products.models import Cart
# Create your views here.
#



def OrderCreate(request):
    cart= Cart(request)
    if request.method == 'POST':
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = form.save()
            for item in cart:
                ProductinOrder.objects.create(order=order,
                                               product=product.product_name,
                                                price_per_item=product.product_price,
                                                quantity=product.product_quantity)
            cart.clear()
            return render(request, )

ClothesStore/ClothesStore/apps/Products/views.py
from django.shortcuts import render
from django.http import Http404, HttpResponseRedirect, HttpResponse, JsonResponse
from .models import *
from django.urls import reverse
from Users.models import SimpleUser
from decimal import Decimal

def index(request):
    # list_products = Product.objects.order_by("-created")[:5]
    # all_list_products = Product.objects.order_by("-id")[:20]
    list_products=ProductImage.objects.filter(is_active=True, is_main=True, product__available=True)
    list_products_outerwear = list_products.filter(product__category__id=7)
    context={'list_products':list_products ,
             'lpo': list_products_outerwear,
             }
    # popular_products = Like.objects.filter(heart_click__gt=3).order_by('-heart_click')[:4]
    # art = get_object_or_404(Product, pk=article_id)
    # art.numberOfClicks +=1
    # art.save()
    return render(request, 'index.html', context)
# 'popular_products'=popular_products


def women_view(request):
    list_products=ProductImage.objects.filter(is_active=True, is_main=True, product__available=True, product__product_gender='Woman')
    list_products_outerwear = list_products.filter(product__category__id=7)
    context={'list_products':list_products ,
             'lpo': list_products_outerwear,
             }
    return render(request, 'Women_page.html', context)


def kids_view(request):
    list_products=ProductImage.objects.filter(is_active=True, is_main=True, product__available=True, product__product_gender='Kid')
    list_products_outerwear = list_products.filter(product__category__id=7)
    context={'list_products':list_products ,
             'lpo': list_products_outerwear,
             }
    return render(request, 'kids_page.html', context)

def detail(request, product_id):
    try:
        a=Product.objects.get(id= product_id)
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
        raise Http404("Page is not found!")
    list_comments=a.comment_set.order_by('-comment_pub_date')[:10]
    context= {'cart': cart,
              'list_products':a,
              'list_comments':list_comments,
              }
    return render(request,'detail.html', context)

def leave_comment(request, product_id):
    if request.method == 'POST':
        try:
            a=Product.objects.get(id=product_id)
        except:
            raise Http404("Product didn`t find")
        a.comment_set.create(author_name = SimpleUser.objects.get(username = request.POST['username']), comment_text = request.POST['comments_text'])
        a.save()
    return HttpResponseRedirect(reverse('Products:detail' , args=(a.id,)))




def search(request,product_name):
    search_byname=list(Product.objects.filter(product_name__contains=product_name).values_list('product_name'))
    try:
        products =""
        print("We are here", search_byname)
        for i in search_byname:
            print(*i)
            products= products + "<h3>%i: "%(search_byname.index(i)+1) + "</h3><br>"
            print(products)
        return HttpResponse("<h2>This is the resoult of search</h2> %s" % products)
    except:
        return HttpResponse("No such products")

def base_view(request):
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id=cart.id
        request.session['cart_id'] = cart_id
        cart=Cart.objects.get(slug=product_slug)
    context = {
               'cart':cart
               }
    return render(request, 'base.html', context)



def cart_view(request):
	try:
		cart_id = request.session['cart_id']
		cart = Cart.objects.get(id=cart_id)
		request.session['total'] = cart.items.count()
	except:
		cart = Cart()
		cart.save()
		cart_id = cart.id
		request.session['cart_id'] = cart_id
		cart = Cart.objects.get(id=cart_id)

	# product = Product.objects.get(slug=product_slug)

	context= {
	'cart': cart,
	# 'product': product,
	}

	return render(request, 'cart.html', context)

def add_to_cart_view(request):
	try:
		cart_id = request.session['cart_id']
		cart = Cart.objects.get(id=cart_id)
		request.session['total'] = cart.items.count()
	except:
		cart = Cart()
		cart.save()
		cart_id = cart.id
		request.session['cart_id'] = cart_id
		cart = Cart.objects.get(id=cart_id)

	product_slug = request.GET.get('product_slug')
	product = Product.objects.get(slug=product_slug)
	cart.add_to_cart(product.slug)

	# ИТОГОВЫЙ ЦЕНА
	new_cart_total =0.00
	for item in cart.items.all():
		new_cart_total += float(item.item_total)
	cart.cart_total = new_cart_total
	cart.save()

	return JsonResponse({'cart_total': cart.items.count(),'cart_total_price': cart.cart_total})


def remove_from_cart_view(request):
	try:
		cart_id = request.session['cart_id']
		cart = Cart.objects.get(id=cart_id)
		request.session['total'] = cart.items.count()
	except:
		cart = Cart()
		cart.save()
		cart_id = cart.id
		request.session['cart_id'] = cart_id
		cart = Cart.objects.get(id=cart_id)


	product_slug = request.GET.get('product_slug')
	product = Product.objects.get(slug=product_slug)
	cart.remove_from_cart(product.slug)

	# ИТОГОВЫЙ ЦЕНА
	new_cart_total =0.00
	for item in cart.items.all():
		new_cart_total += float(item.item_total)
	cart.cart_total = new_cart_total
	cart.save()


	return JsonResponse({'cart_total': cart.items.count(),'cart_total_price': cart.cart_total})

def change_item_qty(request):
	try:
		cart_id = request.session['cart_id']
		cart = Cart.objects.get(id=cart_id)
		request.session['total'] = cart.items.count()
	except:
		cart = Cart()
		cart.save()
		cart_id = cart.id
		request.session['cart_id'] = cart_id
		cart = Cart.objects.get(id=cart_id)

	qty = request.GET.get('qty')
	item_id = request.GET.get('item_id')
	# print(qty, item_id)
	cart_item = CartItem.objects.get(id=int(item_id))
	cart_item.qty = int(qty)
	cart_item.item_total = int(qty) * Decimal(cart_item.product.price)
	cart_item.save()

	# ИТОГОВЫЙ ЦЕНА
	new_cart_total =0.00
	for item in cart.items.all():
		new_cart_total += float(item.item_total)
	cart.cart_total = new_cart_total
	cart.save()

	return JsonResponse(
		{'cart_total': cart.items.count(),
		'item_total': cart_item.item_total,
		'cart_total_price': cart.cart_total
		})

ClothesStore/ClothesStore/templates/base.html
{% load static %}
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zxx">
<head>
	<title>{% block title %}"Sannin" is the top Product Store {% endblock %}</title>
	<meta charset="UTF-8">
	<meta name="description" content=" Divisima | eCommerce Template">
	<meta name="keywords" content="divisima, eCommerce, creative, html">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<!-- Favicon -->
	<link href="{% static 'img/logo_S.png' %}" rel="shortcut icon">

	<!-- Google Font -->
	<link href="https://fonts.googleapis.com/css?family=Josefin+Sans:300,300i,400,400i,700,700i" rel="stylesheet">


	<!-- Stylesheets -->
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"/>
	<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}"/>
	<link rel="stylesheet" href="{% static 'css/flaticon.css' %}"/>
	<link rel="stylesheet" href="{% static 'css/slicknav.min.css' %}"/>
	<link rel="stylesheet" href="{% static 'css/jquery-ui.min.css' %}"/>
	<link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}"/>
	<link rel="stylesheet" href="{% static 'css/animate.css' %}"/>
	<link rel="stylesheet" href="{% static 'css/style.css' %}"/>

{% block header %}{% endblock %}
	<!--[if lt IE 9]>
		  <script  src=" {% static 'https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js' %}"></script>
	  <script  src=" {% static 'https://oss.maxcdn.com/respond/1.4.2/respond.min.js' %}"></script>
	<![endif]-->

</head>
<body>
	<!-- Page Preloder -->
	<div id="preloder">
		<div class="loader"></div>
	</div>

	<!-- Header section -->
	<header class="header-section">
		<div class="header-top">
			<div class="container">
				<div class="row">
					<div class="col-lg-2 text-center text-lg-left">
						<!-- logo -->
						<a href="{% url 'Products:index' %}" class="site-logo">
							<img  src=" {% static 'img/sannin.png' %}" alt="">
						</a>
					</div>
					<div class="col-xl-6 col-lg-5">
						<form class="header-search-form">
							<input type="text" placeholder="Search in Sannin ....">
							<button><i class="flaticon-search"></i></button>
						</form>
					</div>
					<div class="col-xl-4 col-lg-5">
						<div class="user-panel">
							<div class="up-item">
								{%block login%}
                {% if user.is_authenticated%}
                <ul class="nav navbar-nav navbar-right">

                      <a href="{% url 'Users:logout' %}"> Logout </a>
										</ul>
											<ul class="nav navbar-nav navbar-right">
                      <a href="{% url 'Users:profile' %}">{{user.username}}</a>
										</ul>

								<div class="up-item">
									<div class="shopping-card">
										<i class="flaticon-bag"></i>
									</div>
									<a href='{% url "Products:cart" %}'><div >



									Shopping Cart	<span id="cart_count">( {{ cart.items.count }} ) </span></div></a>
								</div>



                {%else%}
								<i class="flaticon-profile"></i>
								<a href="{% url 'Users:signIn' %}">Sign In</a> or <a href="{% url 'Users:register' %}">Create Account</a>

                {%endif%}
                {%endblock%}
								</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<nav class="main-navbar">
			<div class="container">
				<!-- menu -->
				<ul class="main-menu">
					<li><a href="{% url 'Products:index' %}">Home</a></li>
					<li><a href="{% url 'Products:women' %}">Women</a></li>
					<li><a href="{% url 'Products:index' %}">Men</a></li>
					<li><a href="{% url 'Products:kids' %}">Kids
						<span class="new">New</span>
					</a></li>
					<li><a href="{% static '#">Shoes</a>
						<ul class="sub-menu">
							<li><a href="{% static '#">Sneakers</a></li>
							<li><a href="{% static '#">Sandals</a></li>
							<li><a href="{% static '#">Formal Shoes</a></li>
							<li><a href="{% static '#">Boots</a></li>
							<li><a href="{% static '#">Flip Flops</a></li>
						</ul>
					</li>
					<li><a href="{% static '#">Pages</a>
						<ul class="sub-menu">
							<li><a href="{% static './product.html">Product Page</a></li>
							<li><a href="{% static './category.html">Category Page</a></li>
							<li><a href="{% static './cart.html">Cart Page</a></li>
							<li><a href="{% static './checkout.html">Checkout Page</a></li>
							<li><a href="{% static './contact.html">Contact Page</a></li>
						</ul>
					</li>
					<li><a href="{% static '#">Blog</a></li>
				</ul>
			</div>
		</nav>
	</header>
	{% if messages %}
		{% for message in messages %}
			<div class="alert alert-{{ message.tags }}" >
{{ message }}
			</div>
		{% endfor %}
	{% endif %}


    {% block content%}My site{% endblock %}




		<section class="footer-section">
			<div class="container">
				<div class="footer-logo text-center">
					<a href="{% url 'Products:index' %}"><img  src=" {% static './img/mini-sannin.png' %}" alt=""></a>
				</div>
				<div class="row">
					<div class="col-lg-3 col-sm-6">
						<div class="footer-widget about-widget">
							<h2>About</h2>
							<p>Donec vitae purus nunc. Morbi faucibus erat sit amet congue mattis. Nullam frin-gilla faucibus urna, id dapibus erat iaculis ut. Integer ac sem.</p>
							<img  src=" {% static 'img/cards.png' %}" alt="">
						</div>
					</div>
					<div class="col-lg-3 col-sm-6">
						<div class="footer-widget about-widget">
							<h2>Questions</h2>
							<ul>
								<li><a href="{% static '">About Us</a></li>
								<li><a href="{% static '">Track Orders</a></li>
								<li><a href="{% static '">Returns</a></li>
								<li><a href="{% static '">Jobs</a></li>
								<li><a href="{% static '">Shipping</a></li>
								<li><a href="{% static '">Blog</a></li>
							</ul>
							<ul>
								<li><a href="{% static '">Partners</a></li>
								<li><a href="{% static '">Bloggers</a></li>
								<li><a href="{% static '">Support</a></li>
								<li><a href="{% static '">Terms of Use</a></li>
								<li><a href="{% static '">Press</a></li>
							</ul>
						</div>
					</div>
					<div class="col-lg-3 col-sm-6">
						<div class="footer-widget about-widget">
							<h2>Questions</h2>
							<div class="fw-latest-post-widget">
								<div class="lp-item">
									<div class="lp-thumb set-bg" data-setbg="{% static 'img/blog-thumbs/1.jpg' %}"></div>
									<div class="lp-content">
										<h6>what shoes to wear</h6>
										<span>Oct 21, 2018</span>
										<a href="{% static '#" class="readmore">Read More</a>
									</div>
								</div>
								<div class="lp-item">
									<div class="lp-thumb set-bg" data-setbg="{% static 'img/blog-thumbs/2.jpg' %}"></div>
									<div class="lp-content">
										<h6>trends this year</h6>
										<span>Oct 21, 2018</span>
										<a href="{% static '#" class="readmore">Read More</a>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div class="col-lg-3 col-sm-6">
						<div class="footer-widget contact-widget">
							<h2>Questions</h2>
							<div class="con-info">
								<span>C.</span>
								<p>Cannin </p>
							</div>
							<div class="con-info">
								<span>B.</span>
								<p>Almaty, Kazakhstan Manasa 34/1 </p>
							</div>
							<div class="con-info">
								<span>T.</span>
								<p>+77077777777</p>
								<span>T.</span>
								<p>+77077785757</p>
							</div>
							<div class="con-info">
								<span>E.</span>
								<p>alisher@mail.ru</p>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="social-links-warp">
				<div class="container">
					<div class="social-links">
						<a href="" class="instagram"><i class="fa fa-instagram"></i><span>instagram</span></a>
						<a href="" class="google-plus"><i class="fa fa-google-plus"></i><span>g+plus</span></a>
						<a href="" class="pinterest"><i class="fa fa-pinterest"></i><span>pinterest</span></a>
						<a href="" class="facebook"><i class="fa fa-facebook"></i><span>facebook</span></a>
						<a href="" class="twitter"><i class="fa fa-twitter"></i><span>twitter</span></a>
						<a href="" class="youtube"><i class="fa fa-youtube"></i><span>youtube</span></a>
						<a href="" class="tumblr"><i class="fa fa-tumblr-square"></i><span>tumblr</span></a>
					</div>

		<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
		<p class="text-white text-center mt-5">Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a></p>
		<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->

				</div>
			</div>
		</section>
		<!-- Footer section end -->

		<script src=" {% static 'js/scripts.js' %}"></script>
    <script src=" {% static 'js/jquery-3.2.1.min.js' %}"></script>
  	<script src=" {% static 'js/bootstrap.min.js' %}"></script>
  	<script src=" {% static 'js/jquery.slicknav.min.js' %}"></script>
  	<script src=" {% static 'js/owl.carousel.min.js' %}"></script>
  	<script src=" {% static 'js/jquery.nicescroll.min.js' %}"></script>
  	<script src=" {% static 'js/jquery.zoom.min.js' %}"></script>
  	<script src=" {% static 'js/jquery-ui.min.js' %}"></script>
  	<script src=" {% static 'js/main.js' %}"></script>
  </body>
</html>

ClothesStore/ClothesStore/templates/product-item.html
<div class="product-item">
  <div class="pi-pic">

    <!-- <div class="tag-sale">ON SALE</div> -->

<a href="{% url 'Products:detail' lp.product.id %}"><img  src=" {{lp.product_image.url }}" alt=""></a>
{% if lp.product.discount %}
<div class="tag-new">{{lp.product.discount}}%</div>
{%endif%}
<div class="pi-links">
  <a href="{% static '#" class="add-card"><i class="flaticon-bag"></i><span>ADD TO CART</span></a>
<a href="#" class="wishlist-btn"><i class="flaticon-heart"></i></a>
  </div>
</div>
<div class="pi-text">
  <h6>Tg {{lp.product.product_price}}</h6>
  <p>{{lp.product.product_name}} </p>
</div>
</div>